<h1 style="text-align:center">
    Movies
</h1>

<br>

<font color="darkblue">

<h3 style="text-align:center">
    Nombre Apellido1 Apellido2
</h3>
    
<h3 style="text-align:center">
    Fecha
</h3>

<hr>

# Introducción

<br>

En este proyecto se desarrolla en Python un análisis básico de datos sobre películas de cine de IMDB.
El set de datos que vamos a usar inicialmente se encuentra en la siguiente página:

https://www.kaggle.com/datasets/carolzhangdc/imdb-5000-movie-dataset

En ella puede encontrarse información más detallada, así como una descripción precisa de cada columna.

<font color="green">
Seguidamente, te toca a ti hacer una breve introducción, completando el fragmento de letra en azul y desarrollándolo a tu antojo. Suprime después este fragmento en verde.
</font>

<br>

Se plantean los apartados iniciales para su resolución *sin usar la libreria pandas*. Esto se propone así para forzar a practicar con las técnicas, herramientas y conceptos básicos de Python. Más adelante, hay otros apartados propuestos para su resolución con esta librería y otras.

<br>

<font color="darkblue">
A partir de los datos proporcionados, he conseguido ... pero no he podido ...

<br>

Aunque al final de este notebook detallaré la calificación que calculo honestamente, globalmente, siguiendo las puntuaciones que se asigna a cada apartado, diría que he obtenido una nota de *** sobre 10.
</font>

<br>

<font color="green">
Completa tus datos personales en la cabecera, bajo el rótulo inicial. Completa también el breve apartado anterior, con texto  azul, y pon en azul todos los comentarios tuyos, dejando en negro los míos, del enunciado. También, suprime los fragmentos en verde, como éste, que son indicaciones pero que, una vez atendidas, deben desaparecer de la solución que entregas.
</font>

# Datos de partida

(**Nota previa:** hasta el apartado específico de dataframes, se deben desarrollar las soluciones a los ejercicios propuestos sin usar la librería `pandas`, justamente para obligar a practicar con conceptos básicos de Python.)

Nuestra tabla de datos es el archivo de texto `movie_data.csv` que se encuentra en la carpeta `data_in`, y puede verse así con cualquier editor:

<br>

<center>
    <img src="./images/texto.png" width="100%">
</center>

La primera fila es la cabecera.
Esta fila cabecera contiene los nombres de los campos, separados por comas.
Yo la he marcado en azul para distinguirla fácilmente de las demás filas, que contienen los datos propiamente dichos,
esto es, los valores de dichos campos, consignando los datos de cada película en cada línea.

Si abrimos esta tabla con *excell* (importar datos csv con el separador `,`), vemos cada dato en una celda.

<br>

<center>
    <img src="./images/csv_1.png" width="100%">
</center>

<br>

Mostramos la hoja excell en dos imágenes por ser muy ancha.

<br>

<center>
    <img src="./images/csv_2.png" width="100%">
</center>

# Librerías y constantes globales

<br>

Pongamos todas las librerías necesarias al principio, tal como propone el estilo `pep-8`. Ej.:
<a href="https://www.python.org/dev/peps/pep-0008/">PEP 8 -- Style Guide for Python Code</a>.
    
De paso, en éste y otros lugares de Internet podrás encontrar detalles sobre estilo y presentación de código con un estilo estándar y cuidado. Examina esta página y trata de seguir esas indicaciones.

In [2080]:
# Librerías:
import csv
import re
import matplotlib.pyplot as plt
from collections import defaultdict
import requests
from bs4 import BeautifulSoup
import pandas as pd
import mrjob
import numpy as np

In [2081]:
# Constantes globales:
MOVIES_DATA = "data_in/movie_data.csv"
main_fields=["movie_title", "title_year", "director_name", "actor_1_name", "language", "country", "color", "budget", "imdb_score", "movie_imdb_link"]
# Esta celda debe ser completada por el estudiante
pd.set_option('future.no_silent_downcasting', True)

# Parte A. Ejercicios básicos sin usar `pandas` [2 puntos]

Esta parte inicial debe realizarse sin usar la librería `pandas`. Para practicar con esta librería, se plantean otros apartados más abajo.

### A.1. Exploración inicial básica del archivo de datos

Deseamos cargar el archivo de datos, que tiene un formato `csv`.
En este apartado, te recomiendo fuertemente usar la librería `cvs`,
que deberás importar en la primera celda del script, más arriba, no aquí.
(En los siguientes apartados, ya no mencionaré qué librerías usar
ni recordaré dónde se han de importar.)

Observa también que el test de funcionamiento te da el nombre de la función que deber definir
y algún otro identificador como es, por ejemplo, la constante `MOVIES_DATA`,
que debes definir también más arriba, en la segunda celda de este script.

Finalmente, observando el test, verás que se carga por separado la cabecera y las filas de datos.

Ahora, querríamos ver las posiciones de los identificadores de los campos, dados en la línea cabecera.

### A.2. Campos principales de una película

Los campos (columnas) del archivo son demasiados. No nos interesan todos ellos. Dada una lista con todos los campos, se pide extraer otra lista sólo con los campos con los que vamos a trabajar en los siguientes apartados: `movie_title`, `title_year`, `director_name`, `actor_1_name`, `language`, `country`, `color`, `budget`, `imdb_score` y `movie_imdb_link`.

### A.3. Algunos ajustes en los campos

Observa la anomalía en el string del título de la película. También, queremos tratar algunos campos como numéricos, ya sea enteros (el año y el presupuesto) o reales (la valoración). (Algunos campos numéricos enteros están vacíos en el archivo de datos; para ellos, el valor imputado será `-1`.) Además, en las urls de las películas no necesitaremos el fragmento final, iniciado con `?ref_`.

### A.4. Recuperación de alguna información básica

<br>

Diseña funciones para recuperar la siguiente información:

<itemize>
    <li> El conjunto de valores posibles del campo `Color`.
    <li> Los títulos de película de nuestro archivo (limpios de caracteres extraños),
        junto con la cantidad de calificadores (un entero), que contengan la subcadena "Victor".
</itemize>

# B Datos en un diccionario [2 puntos]

### B.1. Carga únicamente de datos que vamos a usar

En lugar de cargar *todos* los datos del archivo, luego generar otro archivo con los datos que nos interesan y luego ajustarlos, es mejor diseñar una función que recorre el archivo de datos y, de cada línea del archivo, *únicamente* retiene la parte que nos interesa, cargando la cabecera por un lado y, por otro, la lista de datos de interés, ajustados como ya hemos dicho.

Cargaremos esta información en un diccionario, cuyas claves serán pares `(título, año)` y cuyos valores se recogen en una lista con el resto de los campos.

Además, los datos de cada película tras la clave `(título, año)` están repetidas en el archivo de datos, con todos los datos idénticos; y lo que es peor: alguna que está repetida, pero con algún dato distinto. En ambos casos, para simplificar, adoptamos el criterio de registrar únicamente la primera aparición de los datos de una misma película y año.

Y ahora podemos suprimir la variable `full_list_data`

### B.2. Recuperación de alguna información 

Diseña funciones para averiguar la siguiente información:

- ¿Qué títulos de películas han sido dirigidas por "James Cameron" (o por el director que se desee)?

- ¿Qué directores han dirigido el número máximo de películas?

- Para cada año de un intervalo dado de años, ¿cuántas películas se han realizado? Esta información debe recuperrase en un diccionario convencional (no por defecto), y luego debe mostrarse en una lista con los años en orden ascendente..

- Diseña también una operación que, partiendo de nuestro diccionario de los datos principales, almacene en un archivo los datos siguientes de cada película, sin la cabecera: el título, el idioma, el año, el país y el presupuesto. El separador será en este caso el carácter `|`. El archivo usado para el almacenamiento es el siguiente:

    ``` python
    FEW_FIELDS = "algunos_campos.txt"
    ```

### B.3. Un conteo sencillo con `defaultdict`

Deseamos saber con qué directores y número de veces ha actuado cada actor como actor principal. Se pide realizar este conteo en un `defaultdict` cuyas claves serán nombres de los actores y cuyos valores tendrán la estructura de un `defaultdict`, cuyas claves serán los nombres de los directores y cuyos valores serán los núneros contabilizados.

### B.4. Print seleccionado

Demasiada información. Deseamos imprimir únicamente, para cada actor, las colaboraciones que superen un mínimo, dato entrada. Si un actor no tiene ninguna colaboración que supere dicho mínimo, lógicamente no debe mostrarse.

# C. Algunos gráficos sencillos [1 punto]


### C.1 Un modelo de gráfica

Vamos a diseñar un modelo de gráfica sencillo que nos sirva para las siguientes representaciones. Tomará como parámetro una lista de pares $(x, y)$, y opcionalmente los tres rótulos explicativos que necesitamos incluir. Además, queremos que las etiquetas de las abcisas aparezcan inclinadas, para poder luego mostrar intervalos de edad.

Las pruebas de funcionamiento te darán más información que las explicaciones que pueda yo dar aquí.

### Una gráfica concreta

Deseamos representar el número de películas de nuestra base de datos que se han producido en un intervalo de años dado.

# D. Acceso a las urls de imdb y webscraping [2 puntos]

### D.1. Recuperación de las URLs

Con sencillas instrucciones, deseamos recuperar todas las *urls* de las películas de nuestro archivo, mostrando cuántas son, la primera de ellas o las diez primeras por ejemplo:

### D.2. Carga de la estructura sintáctica de una URL

Ahora, deseamos extraer el código `html` de una película.

### D.3. Extracción de algunas piezas de información de una URL

Y ahora, con dicho código, deseamos extraer la siguiente información, referida a la película `first_url_movie`:

- La etiqueta completa del título de la película
- La descripción (sólo el contenido).
- La lista de los actores del *reparto principal*
- La información sobre el presupuesto

### D.4. Actores que intervienen en una lista de URLs

Necesitamos crear un archivo con los actores del reparto principal de las películas de IMDB, dada la lista de sus URLs.

# E. Pandas [2 puntos]

### E.1. El primer paso es la carga del archivo en un dataframe

In [2082]:
# Esta celda debe ser completada por el estudiante
# MOVIES_DATA = "data_in/movie_data.csv"
# movie_title	color	director_name	language	country	actor_1_name	movie_imdb_link
def load_dataframe(csv_name):
    df = pd.read_csv(csv_name)
    return df

In [2083]:
# Test de funcionamiento
tabla_completa = load_dataframe(MOVIES_DATA)

tabla_completa

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

### E.2. Tabla de los campos principales

A pertir de la tabla anterior, construimos otra con sólo algumos de los campos:

In [2084]:
# Esta celda debe ser completada por el estudiante
def fields_selected_dataframe(full_data_frame):
    return full_data_frame[main_fields]

In [2085]:
# test de comprobación

tabla_breve = fields_selected_dataframe(tabla_completa)

tabla_breve

,movie_title,title_year,director_name,actor_1_name,language,country,color,budget,imdb_score,movie_imdb_link
0,Avatar,2009.0,James Cameron,CCH Pounder,English,USA,Color,237000000.0,7.9,http://www.imdb.com/title/tt0499549/?ref_=fn_t...
1,Pirates of the Caribbean: At World's End,2007.0,Gore Verbinski,Johnny Depp,English,USA,Color,300000000.0,7.1,http://www.imdb.com/title/tt0449088/?ref_=fn_t...
2,Spectre,2015.0,Sam Mendes,Christoph Waltz,English,UK,Color,245000000.0,6.8,http://www.imdb.com/title/tt2379713/?ref_=fn_t...
3,The Dark Knight Rises,2012.0,Christopher Nolan,Tom Hardy,English,USA,Color,250000000.0,8.5,http://www.imdb.com/title/tt1345836/?ref_=fn_t...
4,Star Wars: Episode VII - The Force Awakens ...,NaN,Doug Walker,Doug Walker,NaN,NaN,NaN,NaN,7.1,http://www.imdb.com/title/tt5289954/?ref_=fn_t...
...,...,...,...,...,...,...,...,...,...,...
5038,Signed Sealed Delivered,2013.0,Scott Smith,Eric Mabius,English,Canada,Color,NaN,7.7,http://www.imdb.com/title/tt3000844/?ref_=fn_t...
5039,The Following,NaN,NaN,Natalie Zea,English,USA,Color,NaN,7.5,http://www.imdb.com/title/tt2071645/?ref_=fn_t...
5040,A Plague So Pleasant,2013.0,Benjamin Roberds,Eva Boehnke,English,USA,Color,1400.0,6.3,http://www.imdb.com/title/tt2107644/?ref_=fn_t...
5041,Shanghai Calling,2012.0,Daniel Hsia,Alan Ruck,English,USA,Color,NaN,6.3,http://www.imdb.com/title/tt2070597/?ref_=fn_t...
5042,My Date with Drew,2004.0,Jon Gunn,John August,English,USA,Color,1100.0,6.6,http://www.imdb.com/title/tt0378407/?ref_=fn_t...

### E.3. Columnas de una tabla

¿Cuáles son las columnas de nuestrsa `tabla_breve`?

In [2086]:
# Esta celda debe ser completada por el estudiante
tabla_breve.columns

Index(['movie_title', 'title_year', 'director_name', 'actor_1_name',
       'language', 'country', 'color', 'budget', 'imdb_score',
       'movie_imdb_link'],
      dtype='object')

### E.4. Campos missing

Algunos campos muestran un valod `NaN`. Deseamos cambiarlo por una cadena de caracteres: `"Desc"`.

In [2087]:
# Esta celda debe ser completada por el estudiante
tabla_breve = tabla_breve.fillna("Desc")

In [2088]:
# Test de comprobación

tabla_breve

,movie_title,title_year,director_name,actor_1_name,language,country,color,budget,imdb_score,movie_imdb_link
0,Avatar,2009.0,James Cameron,CCH Pounder,English,USA,Color,237000000.0,7.9,http://www.imdb.com/title/tt0499549/?ref_=fn_t...
1,Pirates of the Caribbean: At World's End,2007.0,Gore Verbinski,Johnny Depp,English,USA,Color,300000000.0,7.1,http://www.imdb.com/title/tt0449088/?ref_=fn_t...
2,Spectre,2015.0,Sam Mendes,Christoph Waltz,English,UK,Color,245000000.0,6.8,http://www.imdb.com/title/tt2379713/?ref_=fn_t...
3,The Dark Knight Rises,2012.0,Christopher Nolan,Tom Hardy,English,USA,Color,250000000.0,8.5,http://www.imdb.com/title/tt1345836/?ref_=fn_t...
4,Star Wars: Episode VII - The Force Awakens ...,Desc,Doug Walker,Doug Walker,Desc,Desc,Desc,Desc,7.1,http://www.imdb.com/title/tt5289954/?ref_=fn_t...
...,...,...,...,...,...,...,...,...,...,...
5038,Signed Sealed Delivered,2013.0,Scott Smith,Eric Mabius,English,Canada,Color,Desc,7.7,http://www.imdb.com/title/tt3000844/?ref_=fn_t...
5039,The Following,Desc,Desc,Natalie Zea,English,USA,Color,Desc,7.5,http://www.imdb.com/title/tt2071645/?ref_=fn_t...
5040,A Plague So Pleasant,2013.0,Benjamin Roberds,Eva Boehnke,English,USA,Color,1400.0,6.3,http://www.imdb.com/title/tt2107644/?ref_=fn_t...
5041,Shanghai Calling,2012.0,Daniel Hsia,Alan Ruck,English,USA,Color,Desc,6.3,http://www.imdb.com/title/tt2070597/?ref_=fn_t...
5042,My Date with Drew,2004.0,Jon Gunn,John August,English,USA,Color,1100.0,6.6,http://www.imdb.com/title/tt0378407/?ref_=fn_t...

### E.5. Director $\rightarrow$ películas y número de películas

Función que averigua la lista de títulos de películas de un director dado:

In [2089]:
# Esta celda debe ser completada por el estudiante
def titulos_de_director_df(df, director_name):
    return df[df["director_name"] == director_name][["movie_title"]]

In [2090]:
# Test de comprobación:

tabla_tits = titulos_de_director_df(tabla_breve, "James Cameron")
tabla_tits

                      movie_title
0                         Avatar
26                       Titanic
288   Terminator 2: Judgment Day
291                    True Lies
606                    The Abyss
2486                      Aliens
3575              The Terminator

In [2091]:
list_tits = tabla_tits["movie_title"].to_list()
print(list_tits)

['Avatar\xa0', 'Titanic\xa0', 'Terminator 2: Judgment Day\xa0', 'True Lies\xa0', 'The Abyss\xa0', 'Aliens\xa0', 'The Terminator\xa0']

Deseamos saber qué directores han dirigido el máximo número de películas, junto con ese número de películas.

In [2092]:
# Esta celda debe ser completada por el estudiante
def directors_max_movies_df(df):
    sol = dict(df["director_name"].value_counts())
    sol.pop("Desc")

    max_movies = 0
    for key, value in sol.items():
        if value > max_movies and key:
            sol=[key]
            max_movies = value
        elif value == max_movies:
            sol.append(key)
        else:
            # Añado este break porque se que el metodo .value_counts devuelve un objeto ordenado 
            break
    
    return sol, max_movies

In [2093]:
# test de comprobación:

directors_max_movies_df(tabla_breve)

(['Steven Spielberg'], 26)

# Parte F. Un cálculo masivo con map-reduce [0,5 puntos]

En este apartado se ha de realizar un programa aparte, *basado en la técnica de map-reduce*, que calcule, para cada idioma, en qué países en que se han producido películas y la suma de los presupuestos de dichas películas. Cuando el idioma o el país o el presupuesto no se conozcan, no se considerará esta película.

    C:\...> python language_budget_countries.py -q algunos_campos.txt

El programa funcionará necesariamente con la técnica map-reduce, que podemos poner en juego con la librería `mrjob`.

El funcionamiento del mismo se puede activar también desde aquí:

La siguiente celda me permite ver tu programa cómodamente desde aquí.

# Parte G. Un apartado libre [0.5 puntos]

<br>

<font color="green">
Dejo este apartado a tu voluntad. Inventa tú mismo el enunciado y resuélvelo.
El enunciado deberá estar
<b>relacionado con el análisis de datos y con el tema de este proyecto</b>.
También, la idea es mostrar algún aspecto de programación en Python no contemplado o alguna técnica o librería que no has puesto en juego en los apartados anteriores. Concretamente, se valorará el uso de <b>la librería pandas</b>,
que hemos estudiado de un modo bastante sucinto en este módulo y tratado de forma insuficiente en este proyecto de programación,
o quizá puedes también usar alguna otra librería gráfica,
distinta de matplotlib.
    
En la evaluación, si este apartado está bien o muy bien, anota un 0,3 o 0,4. El 0,5 lo reservaremos para las situaciones en que se presente algo brillante, con alguna idea original o alguna técnica novedosa o complejidad especial o algún gráfico vistoso. Especialmente quien opta a un 9,5 o más, debe esmerarse en plantear este apartado a la altura de esa calificación.
</font>

<br>

<font color="darkblue">
Tras eliminar el párrafo anterior, en verde, sustituye éste por tu enunciado, cuya fuente aparecerá en azul oscuro.
</font>

In [2094]:
# Este apartado debe ser completado por el estudiante
MOVIES_DATA = "data_in/movie_data.csv"
main_fields=["title_year", "director_name", "actor_1_name", "language", "country", "color", "budget", "imdb_score", "genres"]
decision_fields=["budget", "genres"]
result_field = ["imdb_score"]

def crear_df(csv_name, main_fields):
    df = pd.read_csv(csv_name)
    df = df[main_fields]
    return df

def aprobado_en_imdb(df, nota_aprobado):
    df["imdb_score"] = df["imdb_score"]>nota_aprobado
    return df

def df_filter(df, col, element):
    df = df[df[col] == element]
    return df

#def place_element(ref_list, element):
#    k = len(ref_list)-1
#    first_k = k
#    while(k>=0):
#        if ref_list[k][1]<element[1]:
#            k-=1
#            if k==-1:
#                ref_list.insert(0, element)
#                ref_list.pop()
#                break
#        elif k == first_k:
#            break
#        else:
#            ref_list.insert(k+1, element)
#            ref_list.pop()
#            break
#    
#    return ref_list



def create_genres_columns(df, n):
    posible_genres = defaultdict(int)
    for each_genres in df["genres"]:
        each_genres = each_genres.split("|")
        for each in each_genres:
            posible_genres[each] += 1


    most_genres = list(posible_genres.items())
    most_genres.sort(key=lambda x:x[1], reverse=True)
    most_genres = most_genres[:n]
    most_genres = set(elem[0] for elem in most_genres)

    def change_row_wout_most_genres(most_genres):
        def change_row(row):
            each_genres = row["genres"]
            each_genres = each_genres.split("|")
            intersection  = list(filter(lambda x: x in each_genres, most_genres))

            for elem in intersection:
                row[elem] = True
            
            return row
        return change_row
    print("holla")
    df = df.apply(change_row_wout_most_genres(most_genres), axis=1)
    for genres in most_genres:
        df[genres] = df[genres].fillna(False)
    return df, most_genres
    
    #most_genres = []
    #for elem in posible_genres.items():
    #    print(most_genres)
    #    if len(most_genres)==n:
    #        most_genres = place_element(most_genres, elem)
    #    elif len(most_genres)<n:
    #        most_genres.append(elem)
    #        if len(most_genres)==n:
    #           most_genres.sort(key=lambda x: x[1], reverse=True) 

    

search_col = "director_name"
search_elem = "Steven Spielberg"

df = crear_df(MOVIES_DATA, main_fields)

df = df_filter(df, search_col, search_elem)
df = aprobado_en_imdb(df, 7)
df = df[decision_fields + result_field + [search_col]]
df, most_genres = create_genres_columns(df, 3)

df

holla

,Action,Adventure,Drama,budget,director_name,genres,imdb_score
54,True,True,False,185000000.0,Steven Spielberg,Action|Adventure|Fantasy,False
178,False,True,False,140000000.0,Steven Spielberg,Adventure|Family|Fantasy,False
189,False,True,False,132000000.0,Steven Spielberg,Adventure|Sci-Fi|Thriller,False
194,True,True,False,135000000.0,Steven Spielberg,Action|Adventure|Family|Mystery,True
284,True,False,False,102000000.0,Steven Spielberg,Action|Mystery|Sci-Fi|Thriller,True
373,False,True,True,100000000.0,Steven Spielberg,Adventure|Drama|Sci-Fi,True
523,True,True,False,73000000.0,Steven Spielberg,Action|Adventure|Sci-Fi,False
536,False,False,True,60000000.0,Steven Spielberg,Comedy|Drama,True
545,False,False,True,70000000.0,Steven Spielberg,Drama|History|Thriller,True
589,False,True,False,70000000.0,Steven Spielberg,Adventure|Comedy|Family|Fantasy,False
604,False,False,True,66000000.0,Steven Spielberg,Drama|War,True
648,True,False,True,70000000.0,Steven Spielberg,Action|Drama|War,True
653,False,False,True,65000000.0,Steven Spielberg,Biography|Drama|History|War,True
697,False,True,False,63000000.0,Steven Spielberg,Adventure|Sci-Fi|Thriller,True
911,False,False,True,52000000.0,Steven Spielberg,Biography|Crime|Drama,True
1039,True,True,False,48000000.0,Steven Spielberg,Action|Adventure|Fantasy,True
1224,False,False,True,40000000.0,Steven Spielberg,Drama|History|Thriller,True
1248,False,False,True,36000000.0,Steven Spielberg,Drama|History,True
1556,True,False,False,35000000.0,Steven Spielberg,Action|Comedy|War,False
1749,True,True,False,28000000.0,Steven Spielberg,Action|Adventure,True
1874,False,False,True,22000000.0,Steven Spielberg,Biography|Drama|History,True
2152,True,True,False,18000000.0,Steven Spielberg,Action|Adventure,True
2154,False,False,True,19400870.0,Steven Spielberg,Drama|Sci-Fi,True
2611,False,False,True,15000000.0,Steven Spielberg,Drama,True
2917,False,True,True,8000000.0,Steven Spielberg,Adventure|Drama|Thriller,True
3080,False,False,False,10500000.0,Steven Spielberg,Family|Sci-Fi,True

In [2095]:
# Pruebas de funcionamiento, también tarea del estudiante:
y_series = df["imdb_score"]
y = y_series.tolist()
print(y)
columnas = list(df.columns)
columnas_a_eliminar = [search_col, "genres", "imdb_score"]
[columnas.remove(elem) for elem in columnas_a_eliminar]



columnas_x = df[list(most_genres) + ["budget"]]
encabezado = columnas_x.dtypes
# x = columnas_x.to_numpy
x = []
for index, row in columnas_x.iterrows():
    x.append(row.tolist())


col_name = [] 
col_types = []

for name, col_type in encabezado.items():
    col_types.append(col_type)
    col_name.append(name)

index = 0
for i in col_types:
    if i == object:
        col_types[index]=bool
    elif i== float:
        col_types[index]=float
    index += 1

#print(f"Nuestro encabezado es {encabezado}")
print(f"El col_types es {col_types}")
print(f"El col_name es {col_name}")
print(f"Nuestra x la hemos alamcenado en x")
print(f"Nuestra y la hemos alamcenado en y")


print(x)
x

[False, False, False, True, True, True, False, True, True, False, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True]
El col_types es [<class 'bool'>, <class 'bool'>, <class 'bool'>, <class 'float'>]
El col_name es ['Adventure', 'Action', 'Drama', 'budget']
Nuestra x la hemos alamcenado en x
Nuestra y la hemos alamcenado en y
[[True, True, False, 185000000.0], [True, False, False, 140000000.0], [True, False, False, 132000000.0], [True, True, False, 135000000.0], [False, True, False, 102000000.0], [True, False, True, 100000000.0], [True, True, False, 73000000.0], [False, False, True, 60000000.0], [False, False, True, 70000000.0], [True, False, False, 70000000.0], [False, False, True, 66000000.0], [False, True, True, 70000000.0], [False, False, True, 65000000.0], [True, False, False, 63000000.0], [False, False, True, 52000000.0], [True, True, False, 48000000.0], [False, False, True, 40000000.0], [False, False, True, 36000000.0], [False, True, False, 35000000.0], [True, True, False, 28000000.0], [False, False, True, 22000000.0], [True, True, False, 18000000.0], [False, False, True, 19400870.0], [False, False, True, 15000000.0], [True, False, True, 8000000.0], [False, False, False, 10500000.0]]

[[True, True, False, 185000000.0],
 [True, False, False, 140000000.0],
 [True, False, False, 132000000.0],
 [True, True, False, 135000000.0],
 [False, True, False, 102000000.0],
 [True, False, True, 100000000.0],
 [True, True, False, 73000000.0],
 [False, False, True, 60000000.0],
 [False, False, True, 70000000.0],
 [True, False, False, 70000000.0],
 [False, False, True, 66000000.0],
 [False, True, True, 70000000.0],
 [False, False, True, 65000000.0],
 [True, False, False, 63000000.0],
 [False, False, True, 52000000.0],
 [True, True, False, 48000000.0],
 [False, False, True, 40000000.0],
 [False, False, True, 36000000.0],
 [False, True, False, 35000000.0],
 [True, True, False, 28000000.0],
 [False, False, True, 22000000.0],
 [True, True, False, 18000000.0],
 [False, False, True, 19400870.0],
 [False, False, True, 15000000.0],
 [True, False, True, 8000000.0],
 [False, False, False, 10500000.0]]

In [2096]:
def gini_float(y):
    n = len(y)
    if n == 0:
        return 0
    fr = [y.count(i) for i in set(y)]
    return sum([(fr[i] / n) * (n - fr[i]) for i in range(len(fr))])
    
def gini_bool(y):
    n = len(y)
    if n == 0:
        return 0
    return 1 - (y.count(True)/n)**2 - (y.count(False)/n)**2


def mode_max(y):
    if len(y) == 0:
        return -np.inf
    count = np.bincount(y)
    return np.argmax(count)

def branch(x, y, S, col_types, col_usadas):
    best_score = np.inf
    for j in range(len(x[0])):
        # print(col_usadas)
        if j in col_usadas:
            continue
        if col_types[j] == bool:
            f = gini_bool
        elif col_types[j] == float:
            f = gini_float
        #print(f"cambiamos a la columna {j}")
        left=[]
        right=[]
        y_left=[]
        y_right=[]
        for i in S:
            if col_types[j] == bool:
                    #print(f"vamos a ver este valor {x[i][j]}")
                if x[i][j]:
                    left.append(i)
                    y_left.append(y[i])
                else:
                    right.append(i)  
                    y_right.append(y[i])

                left_score = f(y_left)
                right_score = f(y_right)
                score = left_score + right_score
            elif col_types[j] == float:
                left = []
                right = []
                y_left = []
                y_right = []
                for k in S:
                    #print(f"vamos a ver este valor {x[k][j]}")
                    if x[k][j] < x[i][j]:
                        left.append(k)
                        y_left.append(y[k])
                    else:
                        right.append(k)
                        y_right.append(y[k])
                
                left_score = f(y_left)
                right_score = f(y_right)
                score = left_score + right_score
            #print(f"nuestros scores son:{score}, left {left_score}, right {right_score}")
            if score < best_score:
                best_score = score
                i_1 = i
                j_1 = j
                left_1 = left
                right_1 = right
                left_score_1 = left_score
                right_score_1 = right_score    

    #print(f"En este nodo nos quedamos con un {left_1}, {right_1}, y asu vez tenemos un score de {score}, para la columna {j_1}")
    return [i_1, j_1, left_1, right_1, best_score, left_score_1, right_score_1]


class Stack:
    def __init__(self,parent,indexes,score,col_usadas=[]):
        self.parent=parent
        self.indexes=indexes
        self.score=score
        self.col_usadas = col_usadas


class Node:
    def __init__(self,parent,resultado,col_quest,th,indexes):
        self.parent=parent
        self.resultado=resultado
        self.col_quest=int(col_quest)
        self.th=th
        self.indexes=indexes
        self.left = None
        self.right = None

    def ask_question(self, new_row, node, indice, col_types, col_names):
        print(f"Nos encontramos en el nodo de pregunta numero {indice}")
        if self.resultado:
            print("Creo que me puedo imaginar que la solucion es:")
            return bool(self.center)
        
        if col_types[self.col_quest] == int:
            print(f"¿Es mayor el {col_names[self.col_quest]} que {self.th}?")
            if new_row[self.col_quest]>self.th:
                print("Si")
                return node[self.right].ask_question(new_row, node, self.right, col_types, col_names)
            else:
                print("No")
                return node[self.left].ask_question(new_row, node, self.left, col_types, col_names)

        elif col_types[self.col_quest] == bool:
            print(f"¿Es del genero {col_names[self.col_quest]}?")
            if new_row[self.col_quest]:
                print("Si")
                return node[self.right].ask_question(new_row, node, self.right, col_types, col_names)
            else:
                print("No")
                return node[self.left].ask_question(new_row, node, self.left, col_types, col_names)


def dt(x, y, col_types, alpha=0, n_min=1):
        # A single set of stack is constructed. Decision tree is initialized.
    stack = [Stack(0, list(range(len(x))), gini_bool(y))]  # f is global
    node = []
    k = -1

    while len(stack) > 0:
        popped = stack.pop()
        k = k + 1

        i, j, left, right, score, left_score, right_score = branch(x, y, popped.indexes, col_types, popped.col_usadas)
        col_usadas = popped.col_usadas+[j]
        if abs(popped.score - score) < alpha or len(popped.indexes) < n_min or len(left) == 0 or len(right) == 0 or len(col_usadas)==len(x[0]):
            node.append(Node(popped.parent, True, j, 0, popped.indexes))
            #print(f"El problema que nos esta dando viene de {popped.score - score < alpha},{len(popped.indexes) < n_min} ,{len(left) == 0 or len(right) == 0}")
            #print(f"nuestro score es {score} y nuestro popped score es {popped.score} por lo que nuestra suma se qued acomo {abs(popped.score - score)}")
        else:
            node.append(Node(popped.parent, False, j, x[i][j], popped.indexes))
            stack.append(Stack(k, right, right_score,col_usadas))
            stack.append(Stack(k, left, left_score,col_usadas))


    for h in range(k, 0, -1):
        pa = node[h].parent
        if node[pa].right == None:
            node[pa].right = h
        elif node[pa].left == None:
            node[pa].left = h
        
    for h in range(k + 1):
        if node[h].resultado:
            y_node = [y[index] for index in node[h].indexes]
            #print(f"el nodoy es {y_node}")
            node[h].center = mode_max(y_node)
        else:
            node[h].center = None

    return node



nodes = dt(x, y, col_types, n_min=2)
print(nodes)
new_row = [True, True, False, 185000000.0]
print(nodes[0].ask_question(new_row, nodes, 0, col_types, col_name))
print(f"la longiud de nodos es:{len(nodes)}")
for node in nodes:
    print(f"el padre es {node.parent}, mientras que la j es {node.col_quest}")
    print(node.center)

[<__main__.Node object at 0x000002601D7DF080>, <__main__.Node object at 0x000002601D7DF4D0>, <__main__.Node object at 0x000002601D7DCB60>, <__main__.Node object at 0x000002601D7DE180>, <__main__.Node object at 0x000002601D7DE150>, <__main__.Node object at 0x000002601D7DCB90>, <__main__.Node object at 0x000002601D7DE0F0>, <__main__.Node object at 0x000002601D7DE660>, <__main__.Node object at 0x000002601D7DE690>, <__main__.Node object at 0x000002601D7DCE90>, <__main__.Node object at 0x000002601D7DE060>, <__main__.Node object at 0x000002601D7DCBC0>, <__main__.Node object at 0x000002601D7DD910>]
Nos encontramos en el nodo de pregunta numero 0
¿Es del genero Adventure?
Si
Nos encontramos en el nodo de pregunta numero 6
¿Es del genero Action?
Si
Nos encontramos en el nodo de pregunta numero 10
¿Es del genero Drama?
No
Nos encontramos en el nodo de pregunta numero 11
Creo que me puedo imaginar que la solucion es:
True
la longiud de nodos es:13
el padre es 0, mientras que la j es 0
None
el padre es 0, mientras que la j es 1
None
el padre es 1, mientras que la j es 2
1
el padre es 1, mientras que la j es 2
None
el padre es 3, mientras que la j es 3
1
el padre es 3, mientras que la j es 3
0
el padre es 0, mientras que la j es 1
None
el padre es 6, mientras que la j es 2
None
el padre es 7, mientras que la j es 3
1
el padre es 7, mientras que la j es 3
0
el padre es 6, mientras que la j es 2
None
el padre es 10, mientras que la j es 3
1
el padre es 10, mientras que la j es 3
1

# Datos personales

<br>

<font color="darkblue">

-   **Apellidos:** ......................................
-   **Nombre:** ......................................
-   **Email:** ......................................
-   **Fecha:** ......................................

<br>

<font color="black">
    
### Ficha de autoevaluación

<br>

<font color="green">
Aquí vienen comentarios del estudiante. Lo siguiente es un ejemplo posible obviamente ... elimina este párrafo y redacta el tuyo propio, en azul.
</font>

<br>

<font color="darkblue">
    
|Apartado|Calificación|Comentario|
|-|-|-|
|a)  |2.0  / 2.5  |Completamente resuelto |
|b)  |0.0  / 2.0  |No lo he conseguido |
|c)  |0.0  / 1.5  |No he entendido el enunciado |
|d)  |0.25 / 1.0  |Sólo he conseguido una parte mínima |
|e)  |0.0  / 2.0  |No lo he conseguido |
|f)  |0.5  / 0.5  |No lo he conseguido más que mínimamente |
|g)  |0.0  / 0.5  |No he logrado el correcto funcionamiento |
|**Total** |**2.75** / 10.0|**Suspenso**|
</font>

<br>

<font color="black">
   
### Ayuda recibida y fuentes utilizadas
    
</font>

<br>

<font color="green">
... comentarios del estudiante ...
Pon tú este párrafo con tus propias observaciones. Elimina este párrafo en verde.
</font>

<br>

<font color="black">
    
### Comentario adicional

</font>

<br>

<font color="green">
... Este apartado es optativo. Si lo completas, ponlo en azul; si no, suprímelo con su título.

<br>

In [2097]:
# Esta celda se ha de respetar: está aquí para comprobar
# el funcionamiento de algunas funciones por parte de tu profesor